spring.application.name=social-media
server.port=8081

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

# DataSource Configuration
#spring.datasource.url=jdbc:h2:mem:social-media
#spring.datasource.username=social-media
#spring.datasource.password=s@123

spring.datasource.url=jdbc:mysql://localhost:3306/social-media_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*